ALTER TABLE session_groups
ADD COLUMN IF NOT EXISTS status VARCHAR(1) DEFAULT 'N',
ADD COLUMN IF NOT EXISTS started_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS ended_at TIMESTAMP WITH TIME ZONE;
