-- 建立 session_seats 資料表，用於記錄學生在特定課堂中的座位選擇
CREATE TABLE public.session_seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES public.sessions(id) ON DELETE CASCADE,
    student_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    seat_x INT NOT NULL,
    seat_y INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 為資料表和欄位添加註解，方便理解
COMMENT ON TABLE public.session_seats IS '記錄學生在特定課堂（session）中所選擇的座位。';
COMMENT ON COLUMN public.session_seats.session_id IS '對應到 sessions.id，標示這是哪一堂課。';
COMMENT ON COLUMN public.session_seats.student_id IS '對應到 auth.users(id)，標示是哪位學生。';
COMMENT ON COLUMN public.session_seats.seat_x IS '座位的 X 座標 (column)。';
COMMENT ON COLUMN public.session_seats.seat_y IS '座位的 Y 座標 (row)。';

-- 建立索引以優化查詢效能
CREATE INDEX idx_session_seats_session_id ON public.session_seats(session_id);
CREATE INDEX idx_session_seats_student_id ON public.session_seats(student_id);

-- 建立唯一約束，確保一個學生在一堂課只能選一個座位
ALTER TABLE public.session_seats
ADD CONSTRAINT unique_student_seat_in_session UNIQUE (session_id, student_id);

-- 建立唯一約束，確保一個座位在一堂課只能被一位學生選擇
ALTER TABLE public.session_seats
ADD CONSTRAINT unique_seat_in_session UNIQUE (session_id, seat_x, seat_y);
