-- Fix session_seats table schema to match actual usage throughout the codebase
-- The table was originally created with seat_x/seat_y and student_id(UUID)
-- but the code expects seat_row/seat_col and account_id(BIGINT)

-- Step 1: Drop the problematic constraints and function that depends on old schema
DROP FUNCTION IF EXISTS public.upsert_session_seat(BIGINT, BIGINT, INT, INT);

-- Step 2: Check if we need to rename columns
-- This is a safe approach: create a new table with correct schema and migrate data
-- First, drop the old indexes and constraints
DROP INDEX IF EXISTS public.idx_session_seats_session_id;
DROP INDEX IF EXISTS public.idx_session_seats_student_id;
DROP INDEX IF EXISTS public.idx_session_seats_account_id;

-- Drop constraints
ALTER TABLE IF EXISTS public.session_seats_old DROP CONSTRAINT IF EXISTS unique_student_seat_in_session;
ALTER TABLE IF EXISTS public.session_seats_old DROP CONSTRAINT IF EXISTS unique_seat_in_session;

-- Check if session_seats table exists and drop it
DROP TABLE IF EXISTS public.session_seats_old;
DROP TABLE IF EXISTS public.session_seats;

-- Step 3: Create the corrected session_seats table
CREATE TABLE public.session_seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES public.sessions(id) ON DELETE CASCADE,
    account_id BIGINT NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
    seat_row INT NOT NULL,
    seat_col INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Step 4: Create indexes
CREATE INDEX idx_session_seats_session_id ON public.session_seats(session_id);
CREATE INDEX idx_session_seats_account_id ON public.session_seats(account_id);

-- Step 5: Create unique constraints
ALTER TABLE public.session_seats
ADD CONSTRAINT unique_student_seat_in_session UNIQUE (session_id, account_id);

ALTER TABLE public.session_seats
ADD CONSTRAINT unique_seat_in_session UNIQUE (session_id, seat_row, seat_col);

-- Step 6: Add comments
COMMENT ON TABLE public.session_seats IS '記錄學生在特定課堂（session）中所選擇的座位。';
COMMENT ON COLUMN public.session_seats.session_id IS '對應到 sessions.id，標示這是哪一堂課。';
COMMENT ON COLUMN public.session_seats.account_id IS '對應到 accounts.id，標示是哪位學生。';
COMMENT ON COLUMN public.session_seats.seat_row IS '座位的行號 (row，0-based)。';
COMMENT ON COLUMN public.session_seats.seat_col IS '座位的列號 (column，0-based)。';

-- Step 7: Migrate data from old table if it exists (skip if table was already dropped)
-- This is now optional since we dropped the old table above
-- If you want to preserve data from session_seats_old, handle it before running this migration
-- For now, we just create an empty session_seats table

-- Recreate the upsert function with correct schema
CREATE OR REPLACE FUNCTION public.upsert_session_seat(
    p_session_id BIGINT,
    p_account_id BIGINT,
    p_seat_row INT,
    p_seat_col INT
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    is_taken BOOLEAN;
BEGIN
    -- 1. Lock the table and check if the seat is already taken in this session
    SELECT EXISTS (
        SELECT 1
        FROM public.session_seats
        WHERE session_id = p_session_id
          AND seat_row = p_seat_row
          AND seat_col = p_seat_col
          AND account_id != p_account_id
        FOR UPDATE
    ) INTO is_taken;

    -- 2. If the seat is taken by another student, raise an exception
    IF is_taken THEN
        RAISE EXCEPTION 'Seat is already taken';
    END IF;

    -- 3. Upsert the student's seat selection
    INSERT INTO public.session_seats (session_id, account_id, seat_row, seat_col)
    VALUES (p_session_id, p_account_id, p_seat_row, p_seat_col)
    ON CONFLICT (session_id, account_id)
    DO UPDATE SET
        seat_row = EXCLUDED.seat_row,
        seat_col = EXCLUDED.seat_col,
        created_at = timezone('utc'::text, now());

END;
$$;

COMMENT ON FUNCTION public.upsert_session_seat(BIGINT, BIGINT, INT, INT)
IS 'Atomically upserts a student''s seat in a session, preventing race conditions. Checks if a seat is taken before assigning it.';
